server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    host: ${DB_HOST}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    database: ${DB_DATABASE}
    port: ${DB_PORT}
  keycloak:
    hostname: ${KC_HOST}
    client_id: "${KC_CLIENT}"
    client_secret: "${KC_SECRET}"
    realm: ${KC_REALM}
  api_key: ${API_KEY}